### ISSUE TITLE
Inconsistent Results creating SubAsset

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/ravenwallet-android#29]
First time creating a sub-asset off of TRYTEST.  Created NOTRYJUSTDO Qty: 21B No-reissue, 0 Units.  Got confirmation with TxID.  Never completed.

Second time, Sub-asset: JUSTDOIT Qty: 21B Units: 8 No-reissue.  Got confirmation.  Then a message that transaction failed.

Third time, Sub-asset: BLAH Qty: 21B Units 8  Reissuable.  Got confirmation with TxID, then crashed.  When I went back into the app, the asset was created.

**Comment by ROSHiix** [comment]
The issue was in ipfs
