### ISSUE TITLE
Support Webview Not Loading

### ISSUE THREAD

**Issue by dustinlewis** [RavenProject/ravenwallet-android#46]
Some versions of Android are not loading any of the support pages. The user sees this error: ERR_CLEARTEXT_NOT_PERMITTED

Could be this issue:
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https

**Comment by spyder46n2** [comment]
Fixed in PR #56
