### ISSUE TITLE
unique asset creation error issue

### ISSUE THREAD

**Issue by giwung0701** [RavenProject/ravenwallet-android#61]
Hi. im using ravenwallet-android to send tx..
i sent unique asset creation tx.. and it succeed..
but as you can see below.. the end of right side in the script pub key 's asm .. error marked.
it sometimes happen when i create unique asset with ipfs_hash code.
i checked the hex strings with the offset .. but i don't know why error shows up
do you have any idea about this ?

"value": 0.00000000,
      "n": 3,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 88a19423d47afba4b02c87ffce412a238835e3da OP_EQUALVERIFY OP_CHECKSIG OP_RVN_ASSET [error]",
        "hex": "76a91488a19423d47afba4b02c87ffce412a238835e3da88acc04e72766e711c474957554e47415353455423756e692830303132333435363738392900e1f50500000000000001122031479ede5414b18e9205f0ab03b8cfac02f4c449ae9a993fc91c9b88c84efbcc75",
        "reqSigs": 1,
        "type": "new_asset",
        "asset": {
          "name": "GIWUNGASSET#uni(00123456789)",
          "amount": 1.00000000,
          "expire_time": 123145565922176,
          "units": 0,
          "reissuable": 0,
          "ipfs_hash": "QmRf22bZar3WKmojipms22PkXH1MZGmvsqzQtuSvQE3uhm"
        },
        "addresses": [
          "RMjdYHeqncFyoEA2FobvjC88Bq5yE7quet"
        ]
      }

the full serialize hex is here..
010000000215f5db3a6e4ed8d66eb1e80a79118f612a7d26f311a74ec4b81797b9a2936d2f010000006b483045022100e098e2d28e8879237398eaf92fdc1b7255b171eab9d1d64364a866c5db3dd1b302203aabfed3d4349d2602aceb724f174581e3e3cebd0e65d6255f9785cdbe7dd5a3012103d0da93473c2b53dfa59254890787f8f920cef8ba331fd09e26540579a62c9fafffffffff15f5db3a6e4ed8d66eb1e80a79118f612a7d26f311a74ec4b81797b9a2936d2f020000006b483045022100c8c471e31f9ccb1521ad626960ea3ac3e002f19532ff29db626aebf8e6b1157302207b2f914ff972a370f9ebb89d3a02c5021752e1a055a48fbacf3674a7c709d6c1012103d0da93473c2b53dfa59254890787f8f920cef8ba331fd09e26540579a62c9fafffffffff040065cd1d000000001976a914f62e63b949bfcad8258fbc0d9e4d8f71b64796be88ace4561182090000001976a91488a19423d47afba4b02c87ffce412a238835e3da88ac00000000000000003576a91488a19423d47afba4b02c87ffce412a238835e3da88acc01972766e740c474957554e4741535345542100e1f505000000007500000000000000006a76a91488a19423d47afba4b02c87ffce412a238835e3da88acc04e72766e711c474957554e47415353455423756e692830303132333435363738392900e1f50500000000000001122031479ede5414b18e9205f0ab03b8cfac02f4c449ae9a993fc91c9b88c84efbcc7500000000

**Comment by BonoTechnologies** [comment]
re-Issued to [https://github.com/RavenProject/Ravencoin/issues/710](url)
